services:
  amr-api:
    image: ghcr.io/cesi-workspace/amr-api
    ports:
      - "80:8000"  # Port 80 du conteneur vers le port 80 de l'hôte
  depends_on:
      mariadb:
        condition: service_healthy
  mariadb:
    image: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: amr
      MARIADB_USER: test
      MARIADB_PASSWORD: test
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mariadb-admin", "ping", "-u", "test", "-ptest"]
      timeout: 20s
      retries: 10
