# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    timezone: '%env(APP_TIMEZONE)%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
    App\Subscriber\UserSubscriber:
        tags:
            - { name: doctrine.event_subscriber }
    App\Subscriber\ConnectionSubscriber:
        tags:
            - { name: doctrine.event_subscriber }
    App\Subscriber\MessageSubscriber:
        tags:
            - { name: doctrine.event_subscriber }
    App\Subscriber\ExceptionSubscriber:
        tags: [kernel.event_listener]
    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    App\Service\CryptService:
        arguments:
            $cryptkey: '%env(APP_SECRET)%'
            $cryptalgo: '%env(APP_CRYPTALGO)%'
    App\Service\EmailService:
        arguments:
            $to: '%env(MAIL_ADDRESS_TO)%'
            $from: '%env(MAIL_ADDRESS_FROM)%'

    App\Subscriber\JWTSubscriber:
        tags:
            - { name: kernel.event_listener }