name: PHP push

on:
  push:
    branches:
      - develop

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v3
        with:
          php-version: '8.2.2' # Remplacez cette valeur par votre version PHP préférée

      - name: Install dependencies
        run: composer install

      - name: Run PHPUnit
        run: vendor/bin/phpunit