name: PHP push
run-name: Deploy version ${{ github.ref_name }}

on:
  push:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup project
        uses: ./github/actions/setup-project

      - name: Run PHPUnit
        run: vendor/bin/phpunit