name: PHP push
run-name: test thomas

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup project
        uses: ./github/actions/setup-project

      - name: Run PHPUnit
        run: vendor/bin/phpunit