name: Pull request on recipe

on:
  pull_request:
    branches: [ recipe ]


# cancel workflow when there is already one launched
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup project
        uses: ./.github/actions/setup-project
      - name: Test project
        uses: ./.github/actions/test-project
        with:
          sonarqube_host: ${{ secrets.SONARQUBE_HOST }}
          sonarqube_token: ${{ secrets.SONARQUBE_TOKEN }}
          database_url_test: ${{ secrets.DATABASE_URL_TEST }}