name: Deploy on recipe environment
run-name: Deploy recipe

on:
  pull_request:
    branches: [ recipe ]


# cancel workflow when there is already one launched
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup project
        uses: ./.github/actions/setup-project
      - name: Test project
        uses: ./.github/actions/test-project
        with:
          sonarqube_host: ${{ secrets.SONARQUBE_HOST }}
          sonarqube_token: ${{ secrets.SONARQUBE_TOKEN }}
          database_url_test: ${{ secrets.DATABASE_URL_TEST }}
  deploy:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - name: Login to ghcr, pull and start api
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST_SRV_PROD }}
          username: ${{ secrets.SSH_USER_SRV_PROD }}
          key: ${{ secrets.SSH_KEY_SRV_PROD }}
          script: |
            docker compose -f docker-compose-recipe.yml down
            cd /home
            if [ -d amr-api ]; then
              cd amr-api
              git reset --hard HEAD
              git pull
            else
              git clone https://github.com/cesi-workspace/amr-api.git
              cd amr-api
            fi
            docker compose -f docker-compose-recipe.yml up -d