name: Deploy on production environment
run-name: Deploy version ${{ github.ref_name }}
on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
#    branches: [ recipe ]

# cancel workflow when there is already one launched
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
#  test:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v3
#      - name: Setup project
#        uses: ./.github/actions/setup-project
#      - name: Run tests
#        run: ./vendor/bin/phpunit
  build:
    runs-on: ubuntu-latest
#    needs: [test]
    steps:
      - uses: actions/checkout@v3
      - name: Setup project
        uses: ./.github/actions/setup-project
      - name: Login to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{secrets.GCRH_USER}}
          password: ${{secrets.GCRH_TOKEN}}
      - name: Docker build
        run: |
          docker build . --tag ghcr.io/cesi-workspace/amr-api:${{  github.ref_name }}
          docker push ghcr.io/cesi-workspace/amr-api:${{  github.ref_name }}
  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Login to ghcr, pull and start api
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST_SRV_PROD }}
          username: ${{ secrets.SSH_USER_SRV_PROD }}
          key: ${{ secrets.SSH_KEY_SRV_PROD }}
          script: |
            cd /home/amr-api-prod
            old_line="image: ghcr.io/cesi-workspace/amr-api:.*"
            new_line="image: ghcr.io/cesi-workspace/amr-api:${{github.ref_name}}"
            sudo sed -i "s|$old_line|$new_line|g" docker-compose.yaml
            docker-compose down
            docker image rm $(docker images --filter=reference="ghcr.io/cesi-workspace/amr-api" -q)
            echo ${{secrets.GCRH_TOKEN}} | docker login ghcr.io -u ${{secrets.GCRH_USER}} --password-stdin
            docker pull ghcr.io/cesi-workspace/amr-api:${{  github.ref_name }}
            docker-compose up -d