name: Deploy on production environment
run-name: Deploy version ${{ github.ref_name }}
on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
#    branches: [ recipe ]

# cancel workflow when there is already one launched
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup project
        uses: ./.github/actions/setup-project
      - name: Run tests
        run: ./vendor/bin/phpunit
  build:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - uses: actions/checkout@v3
      - name: Setup project
        uses: ./.github/actions/setup-project
      - name: Login to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
      - name: Docker build
        run: |
          docker build . --tag ghcr.io/cesi-workspace/amr-api:${{  github.ref_name }}
          docker push ghcr.io/cesi-workspace/amr-api:${{  github.ref_name }}