name: Deploy on production environment
run-name: Deploy version ${{ github.ref_name }}
on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
#    branches: [ recipe ]

# cancel workflow when there is already one launched
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup project
        uses: ./.github/actions/setup-project
      - name: Test project
        uses: ./.github/actions/test-project
        with:
          sonarqube_host: ${{ secrets.SONARQUBE_HOST }}
          sonarqube_token: ${{ secrets.SONARQUBE_TOKEN }}
          database_url_test: ${{ secrets.DATABASE_URL_TEST }}
  build:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - uses: actions/checkout@v3
      - name: Setup project
        uses: ./.github/actions/setup-project
      - name: Login to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{secrets.GCRH_USER}}
          password: ${{secrets.GCRH_TOKEN}}
      - name: Docker build
        run: |
          old_line='DATABASE_URL="sqlite:///%kernel.project_dir%/var/data.db"'
          new_line='DATABASE_URL="mysql://${{secrets.MARIADB_PROD_USER}}:${{secrets.MARIADB_PROD_PASSWORD}}@mariadb:3306/amr?serverVersion=8&charset=utf8mb4"'
          sudo sed -i "s|$old_line|$new_line|g" .env
          
          docker build . --tag ghcr.io/cesi-workspace/amr-api:${{  github.ref_name }}
          docker push ghcr.io/cesi-workspace/amr-api:${{  github.ref_name }}
  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Login to ghcr, pull and start api
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST_SRV_PROD }}
          username: ${{ secrets.SSH_USER_SRV_PROD }}
          key: ${{ secrets.SSH_KEY_SRV_PROD }}
          script: |
            mkdir /home/amr-api-prod
            cd /home/amr-api-prod
            rm docker-compose-prod.yml
            curl https://raw.githubusercontent.com/cesi-workspace/amr-api/main/docker-compose-prod.yml > docker-compose-prod.yml
            
            old_line="image: ghcr.io/cesi-workspace/amr-api"
            new_line="image: ghcr.io/cesi-workspace/amr-api:${{github.ref_name}}"
            sudo sed -i "s|$old_line|$new_line|g" docker-compose-prod.yml
            
            old_line="MARIADB_USER:.*"
            new_line="MARIADB_USER: ${{secrets.MARIADB_PROD_USER}}"
            sudo sed -i "s|$old_line|$new_line|g" docker-compose-prod.yml
            
            old_line="MARIADB_PASSWORD:.*"
            new_line="MARIADB_PASSWORD: ${{secrets.MARIADB_PROD_PASSWORD}}"
            sudo sed -i "s|$old_line|$new_line|g" docker-compose-prod.yml
            
            docker compose -f docker-compose-prod.yml down
            docker image rm $(docker images --filter=reference="ghcr.io/cesi-workspace/amr-api" -q)
            echo ${{secrets.GCRH_TOKEN}} | docker login ghcr.io -u ${{secrets.GCRH_USER}} --password-stdin
            docker pull ghcr.io/cesi-workspace/amr-api:${{  github.ref_name }}
            docker compose -f docker-compose-prod.yml up -d