name: Deploy on production environment
run-name: Deploy version ${{ github.ref_name }}
on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: ls -lah
      - name: Setup project
        uses: .github/actions/setup-project
